---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: cow.global.indigo
  namespace: kafka
  labels:
    strimzi.io/cluster: mars-kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
