apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
  labels:
    app: velocity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config
          configMap:
            name: velocity-config
            items:
              - key: velocity.toml
                path: velocity.toml
        - name: icon
          configMap:
            name: server-icon
            items:
              - key: server-icon.png
                path: server-icon.png
      containers:
        - name: velocity
          image: ghcr.io/cownetwork/velocity:1.1.5
          ports:
            - containerPort: 25577
          volumeMounts:
            - name: config
              mountPath: /opt/velocity/velocity.toml
              subPath: velocity.toml
            - name: icon
              mountPath: /opt/velocity/server-icon.png
              subPath: server-icon.png
          
