---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - storage.namespace.yaml
  - postgres.statefulset.yaml
  - postgres.service.yaml
  - redis.configmap.yaml
  - redis.deployment.yaml
  - redis.service.yaml
