apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    appendonly yes
    appendfilename data.aof
    appendfsync everysec
    dir /var/lib/redis    

    maxmemory 1gb
    maxmemory-policy noeviction
