---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
resources:
  - backend.namespace.yaml
    #  - user-service.deployment.yaml
    #  - user-service.service.yaml
  - indigo.deployment.yaml
  - indigo.service.yaml
