---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: reloader   
  name: reloader-reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader-reloader
  template:
    metadata:
      labels:
        app: reloader-reloader           
    spec:
      containers:
      - image: "stakater/reloader:v0.0.77"
        imagePullPolicy: IfNotPresent
        name: reloader-reloader
        ports:
        - name: http
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
      securityContext: 
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: reloader-reloader
